<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create a new position</title>
</head>
<body>
    <div class="body-container">
        <?php 
            if (file_exists($navigation_bar)) {
                require $navigation_bar;
            }
        ?>
        <main>
            <h2>Create a new posistion</h2>
            <form method="POST" action=<?php echo $paths['CONTROLLER_PATH'] . 'add-position.php' ?>>
                <label>Enter position name: </label><br />
                <input type="text" name="position"><br/>
                <label>Number of valid votes: </label><br />
                <input type="text" name="valid_vote"><br />
                <input type="submit" value="Create">
            </form> 
        </main>
    </div>
</body>
</html>